spring:
  cloud:
    function:
      definition: processCustomer;parseProductFRA;parseProductUSA;parseOrder;parseItem
    stream:
      function:
        bindings:
          processCustomer-in-0: customer
          processCustomer-out-0: customer-output
      bindings:
        customer:
          destination: queue.customer.messages
        customer-output:
          destination: queue.products.messages
        parseProductFRA-in-0:
          destination: queue.productFRA-in.messages
        parseProductFRA-out-0:
          destination: queue.orders.messages
        parseProductUSA-in-0:
          destination: queue.parseProductUSA-in.messages
        parseProductUSA-out-0:
          destination: queue.orders.messages
        parseOrder-in-0:
          destination: queue.orders.messages
        parseOrder-out-0:
          destination: queue.items.messages
        parseItem-in-0:
          destination: queue.items.messages
#        sendCustomerData-out-0:
#          destination: queue.customer.messages
logging:
  level:
    root: info
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics