spring:
  cloud:
    function:
       definition: parseItem;sendCustomerData;processCustomer;parseProduct;parseOrder;parseProductFRA;parseProductUSA
    stream:
      bindings:
        processCustomer-in-0:
          destination: queue.customers.messages
        processCustomer-out-0:
          destination: queue.products.messages
        parseProduct-in-0:
          destination: queue.products.messages
        parseProduct-out-0:
          destination: queue.orders.messages
        parseOrder-in-0:
          destination: queue.orders.messages
        parseOrder-out-0:
          destination: queue.items.messages
        parseProductFRA-in-0:
          destination: queue.productFRA-in.messages
        parseProductFRA-out-0:
          destination: queue.orders.messages
        parseProductUSA-in-0:
          destination: queue.parseProductUSA-in.messages
        parseProductUSA-out-0:
          destination: queue.orders.messages
        sendCustomerData-out-0:
          destination: queue.customers.messages
        parseItem-in-0:
          destination: queue.items.messages
logging:
  level:
    root: info